[build]
  publish = "."
  command = "echo 'Static Site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: If you want to proxy API requests like we did before
[[redirects]]
  from = "/api/*"
  to = "http://localhost:8001/:splat"
  status = 200
  force = true
